// Generates React wrappers for every custom element from custom-elements.json.
// Run after `npm run analyze`. Output: src/react/index.ts
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'

const manifest = JSON.parse(readFileSync('custom-elements.json', 'utf8'))

const pascal = (s) =>
  s
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')

const decls = manifest.modules
  .flatMap((mod) =>
    (mod.declarations ?? [])
      .filter((d) => d.customElement && d.tagName)
      .map((d) => ({ tagName: d.tagName, className: d.name, path: mod.path, events: d.events ?? [] }))
  )
  .sort((a, b) => a.tagName.localeCompare(b.tagName))

const importPath = (p) => '../' + p.replace(/^src\//, '').replace(/\.ts$/, '.js')

const lines = []
lines.push('// AUTO-GENERATED by scripts/gen-react.mjs — do not edit by hand.')
lines.push('// React wrappers for Film components (see `npm run gen:react`).')
lines.push("import * as React from 'react'")
lines.push("import { createComponent } from '@lit/react'")
lines.push('')
for (const d of decls) {
  lines.push(`import { ${d.className} } from '${importPath(d.path)}'`)
}
lines.push('')

for (const d of decls) {
  const reactName = pascal(d.tagName)
  const events = d.events
    .map((e) => `      ${JSON.stringify('on' + pascal(e.name))}: ${JSON.stringify(e.name)}`)
    .join(',\n')
  lines.push(`export const ${reactName} = createComponent({`)
  lines.push('  react: React,')
  lines.push(`  tagName: ${JSON.stringify(d.tagName)},`)
  lines.push(`  elementClass: ${d.className}`)
  if (events) {
    lines[lines.length - 1] += ','
    lines.push('  events: {')
    lines.push(events)
    lines.push('  }')
  }
  lines.push('})')
  lines.push('')
}

mkdirSync('src/react', { recursive: true })
writeFileSync('src/react/index.ts', lines.join('\n'))
console.log(`Generated src/react/index.ts with ${decls.length} wrappers`)
