// AUTO-GENERATED by scripts/gen-react.mjs — do not edit by hand.
// React wrappers for Film components (see `npm run gen:react`).
import * as React from 'react'
import { createComponent } from '@lit/react'

import { Accordion } from '../data/accordion.js'
import { AccordionItem } from '../data/accordion-item.js'
import { Alert } from '../feedback/alert.js'
import { Avatar } from '../data/avatar.js'
import { Badge } from '../feedback/badge.js'
import { Box } from '../layout/box.js'
import { Breadcrumb } from '../navigation/breadcrumb.js'
import { BreadcrumbItem } from '../navigation/breadcrumb-item.js'
import { Button } from '../actions/button.js'
import { ButtonGroup } from '../actions/button-group.js'
import { Calendar } from '../forms/calendar.js'
import { Card } from '../data/card.js'
import { Center } from '../layout/center.js'
import { Checkbox } from '../forms/checkbox.js'
import { Cluster } from '../layout/cluster.js'
import { Code } from '../data/code.js'
import { ColorPicker } from '../forms/color-picker.js'
import { Combobox } from '../forms/combobox.js'
import { CopyButton } from '../actions/copy-button.js'
import { Cover } from '../layout/cover.js'
import { DatePicker } from '../forms/date-picker.js'
import { Details } from '../data/details.js'
import { Dialog } from '../overlays/dialog.js'
import { Divider } from '../typography/divider.js'
import { Drawer } from '../overlays/drawer.js'
import { Dropdown } from '../overlays/dropdown.js'
import { Field } from '../forms/field.js'
import { FileInput } from '../forms/file-input.js'
import { Form } from '../forms/form.js'
import { Frame } from '../layout/frame.js'
import { Grid } from '../layout/grid.js'
import { Heading } from '../typography/heading.js'
import { Icon } from '../layout/icon.js'
import { IconButton } from '../actions/icon-button.js'
import { Imposter } from '../layout/imposter.js'
import { Input } from '../forms/input.js'
import { Kbd } from '../typography/kbd.js'
import { Link } from '../actions/link.js'
import { List } from '../data/list.js'
import { ListItem } from '../data/list-item.js'
import { Menu } from '../navigation/menu.js'
import { MenuBar } from '../navigation/menu-bar.js'
import { MenuBarItem } from '../navigation/menu-bar-item.js'
import { MenuItem } from '../navigation/menu-item.js'
import { Nav } from '../navigation/nav.js'
import { NavItem } from '../navigation/nav-item.js'
import { NumberInput } from '../forms/number-input.js'
import { Pagination } from '../navigation/pagination.js'
import { Popconfirm } from '../overlays/popconfirm.js'
import { Popover } from '../overlays/popover.js'
import { ProgressBar } from '../feedback/progress-bar.js'
import { Prose } from '../typography/prose.js'
import { Radio } from '../forms/radio.js'
import { RadioGroup } from '../forms/radio-group.js'
import { Range } from '../forms/range.js'
import { Reel } from '../layout/reel.js'
import { Search } from '../forms/search.js'
import { Select } from '../forms/select.js'
import { SelectOption } from '../forms/select-option.js'
import { Sidebar } from '../layout/sidebar.js'
import { Skeleton } from '../feedback/skeleton.js'
import { Slider } from '../forms/slider.js'
import { Spinner } from '../feedback/spinner.js'
import { SplitPanel } from '../layout/split-panel.js'
import { Stack } from '../layout/stack.js'
import { Step } from '../navigation/step.js'
import { Steps } from '../navigation/steps.js'
import { Switch } from '../forms/switch.js'
import { Switcher } from '../layout/switcher.js'
import { Tab } from '../navigation/tab.js'
import { TabPanel } from '../navigation/tab-panel.js'
import { Table } from '../data/table.js'
import { Tabs } from '../navigation/tabs.js'
import { Tag } from '../feedback/tag.js'
import { Text } from '../typography/text.js'
import { Textarea } from '../forms/textarea.js'
import { Toast } from '../feedback/toast.js'
import { Tooltip } from '../overlays/tooltip.js'
import { Tree } from '../navigation/tree.js'
import { TreeItem } from '../navigation/tree-item.js'
import { VisuallyHidden } from '../typography/visually-hidden.js'
import { Window } from '../windowing/window.js'
import { Workspace } from '../windowing/workspace.js'

export const FilmAccordion = createComponent({
  react: React,
  tagName: "film-accordion",
  elementClass: Accordion
})

export const FilmAccordionItem = createComponent({
  react: React,
  tagName: "film-accordion-item",
  elementClass: AccordionItem,
  events: {
      "onFilmToggle": "film-toggle"
  }
})

export const FilmAlert = createComponent({
  react: React,
  tagName: "film-alert",
  elementClass: Alert
})

export const FilmAvatar = createComponent({
  react: React,
  tagName: "film-avatar",
  elementClass: Avatar
})

export const FilmBadge = createComponent({
  react: React,
  tagName: "film-badge",
  elementClass: Badge
})

export const FilmBox = createComponent({
  react: React,
  tagName: "film-box",
  elementClass: Box
})

export const FilmBreadcrumb = createComponent({
  react: React,
  tagName: "film-breadcrumb",
  elementClass: Breadcrumb
})

export const FilmBreadcrumbItem = createComponent({
  react: React,
  tagName: "film-breadcrumb-item",
  elementClass: BreadcrumbItem
})

export const FilmButton = createComponent({
  react: React,
  tagName: "film-button",
  elementClass: Button
})

export const FilmButtonGroup = createComponent({
  react: React,
  tagName: "film-button-group",
  elementClass: ButtonGroup
})

export const FilmCalendar = createComponent({
  react: React,
  tagName: "film-calendar",
  elementClass: Calendar,
  events: {
      "onFilmChange": "film-change"
  }
})

export const FilmCard = createComponent({
  react: React,
  tagName: "film-card",
  elementClass: Card
})

export const FilmCenter = createComponent({
  react: React,
  tagName: "film-center",
  elementClass: Center
})

export const FilmCheckbox = createComponent({
  react: React,
  tagName: "film-checkbox",
  elementClass: Checkbox,
  events: {
      "onChange": "change"
  }
})

export const FilmCluster = createComponent({
  react: React,
  tagName: "film-cluster",
  elementClass: Cluster
})

export const FilmCode = createComponent({
  react: React,
  tagName: "film-code",
  elementClass: Code
})

export const FilmColorPicker = createComponent({
  react: React,
  tagName: "film-color-picker",
  elementClass: ColorPicker,
  events: {
      "onChange": "change"
  }
})

export const FilmCombobox = createComponent({
  react: React,
  tagName: "film-combobox",
  elementClass: Combobox,
  events: {
      "onChange": "change"
  }
})

export const FilmCopyButton = createComponent({
  react: React,
  tagName: "film-copy-button",
  elementClass: CopyButton,
  events: {
      "onFilmCopy": "film-copy",
      "onFilmError": "film-error"
  }
})

export const FilmCover = createComponent({
  react: React,
  tagName: "film-cover",
  elementClass: Cover
})

export const FilmDatePicker = createComponent({
  react: React,
  tagName: "film-date-picker",
  elementClass: DatePicker,
  events: {
      "onChange": "change"
  }
})

export const FilmDetails = createComponent({
  react: React,
  tagName: "film-details",
  elementClass: Details,
  events: {
      "onFilmToggle": "film-toggle"
  }
})

export const FilmDialog = createComponent({
  react: React,
  tagName: "film-dialog",
  elementClass: Dialog
})

export const FilmDivider = createComponent({
  react: React,
  tagName: "film-divider",
  elementClass: Divider
})

export const FilmDrawer = createComponent({
  react: React,
  tagName: "film-drawer",
  elementClass: Drawer
})

export const FilmDropdown = createComponent({
  react: React,
  tagName: "film-dropdown",
  elementClass: Dropdown,
  events: {
      "onFilmOpen": "film-open",
      "onFilmClose": "film-close"
  }
})

export const FilmField = createComponent({
  react: React,
  tagName: "film-field",
  elementClass: Field
})

export const FilmFileInput = createComponent({
  react: React,
  tagName: "film-file-input",
  elementClass: FileInput,
  events: {
      "onChange": "change"
  }
})

export const FilmForm = createComponent({
  react: React,
  tagName: "film-form",
  elementClass: Form,
  events: {
      "onFilmInvalid": "film-invalid",
      "onFilmSubmit": "film-submit",
      "onFilmReset": "film-reset"
  }
})

export const FilmFrame = createComponent({
  react: React,
  tagName: "film-frame",
  elementClass: Frame
})

export const FilmGrid = createComponent({
  react: React,
  tagName: "film-grid",
  elementClass: Grid
})

export const FilmHeading = createComponent({
  react: React,
  tagName: "film-heading",
  elementClass: Heading
})

export const FilmIcon = createComponent({
  react: React,
  tagName: "film-icon",
  elementClass: Icon
})

export const FilmIconButton = createComponent({
  react: React,
  tagName: "film-icon-button",
  elementClass: IconButton
})

export const FilmImposter = createComponent({
  react: React,
  tagName: "film-imposter",
  elementClass: Imposter
})

export const FilmInput = createComponent({
  react: React,
  tagName: "film-input",
  elementClass: Input,
  events: {
      "onChange": "change",
      "onInput": "input"
  }
})

export const FilmKbd = createComponent({
  react: React,
  tagName: "film-kbd",
  elementClass: Kbd
})

export const FilmLink = createComponent({
  react: React,
  tagName: "film-link",
  elementClass: Link
})

export const FilmList = createComponent({
  react: React,
  tagName: "film-list",
  elementClass: List
})

export const FilmListItem = createComponent({
  react: React,
  tagName: "film-list-item",
  elementClass: ListItem
})

export const FilmMenu = createComponent({
  react: React,
  tagName: "film-menu",
  elementClass: Menu
})

export const FilmMenuBar = createComponent({
  react: React,
  tagName: "film-menu-bar",
  elementClass: MenuBar
})

export const FilmMenuBarItem = createComponent({
  react: React,
  tagName: "film-menu-bar-item",
  elementClass: MenuBarItem,
  events: {
      "onFilmMenubarOpen": "film-menubar-open",
      "onFilmMenubarClose": "film-menubar-close"
  }
})

export const FilmMenuItem = createComponent({
  react: React,
  tagName: "film-menu-item",
  elementClass: MenuItem,
  events: {
      "onFilmSelect": "film-select"
  }
})

export const FilmNav = createComponent({
  react: React,
  tagName: "film-nav",
  elementClass: Nav
})

export const FilmNavItem = createComponent({
  react: React,
  tagName: "film-nav-item",
  elementClass: NavItem
})

export const FilmNumberInput = createComponent({
  react: React,
  tagName: "film-number-input",
  elementClass: NumberInput,
  events: {
      "onChange": "change"
  }
})

export const FilmPagination = createComponent({
  react: React,
  tagName: "film-pagination",
  elementClass: Pagination,
  events: {
      "onFilmPageChange": "film-page-change"
  }
})

export const FilmPopconfirm = createComponent({
  react: React,
  tagName: "film-popconfirm",
  elementClass: Popconfirm,
  events: {
      "onFilmConfirm": "film-confirm",
      "onFilmCancel": "film-cancel"
  }
})

export const FilmPopover = createComponent({
  react: React,
  tagName: "film-popover",
  elementClass: Popover,
  events: {
      "onFilmOpen": "film-open",
      "onFilmClose": "film-close"
  }
})

export const FilmProgressBar = createComponent({
  react: React,
  tagName: "film-progress-bar",
  elementClass: ProgressBar
})

export const FilmProse = createComponent({
  react: React,
  tagName: "film-prose",
  elementClass: Prose
})

export const FilmRadio = createComponent({
  react: React,
  tagName: "film-radio",
  elementClass: Radio
})

export const FilmRadioGroup = createComponent({
  react: React,
  tagName: "film-radio-group",
  elementClass: RadioGroup,
  events: {
      "onChange": "change"
  }
})

export const FilmRange = createComponent({
  react: React,
  tagName: "film-range",
  elementClass: Range,
  events: {
      "onChange": "change",
      "onInput": "input"
  }
})

export const FilmReel = createComponent({
  react: React,
  tagName: "film-reel",
  elementClass: Reel
})

export const FilmSearch = createComponent({
  react: React,
  tagName: "film-search",
  elementClass: Search,
  events: {
      "onChange": "change",
      "onFilmSearch": "film-search",
      "onInput": "input"
  }
})

export const FilmSelect = createComponent({
  react: React,
  tagName: "film-select",
  elementClass: Select,
  events: {
      "onChange": "change"
  }
})

export const FilmSelectOption = createComponent({
  react: React,
  tagName: "film-select-option",
  elementClass: SelectOption
})

export const FilmSidebar = createComponent({
  react: React,
  tagName: "film-sidebar",
  elementClass: Sidebar
})

export const FilmSkeleton = createComponent({
  react: React,
  tagName: "film-skeleton",
  elementClass: Skeleton
})

export const FilmSlider = createComponent({
  react: React,
  tagName: "film-slider",
  elementClass: Slider,
  events: {
      "onFilmChange": "film-change"
  }
})

export const FilmSpinner = createComponent({
  react: React,
  tagName: "film-spinner",
  elementClass: Spinner
})

export const FilmSplitPanel = createComponent({
  react: React,
  tagName: "film-split-panel",
  elementClass: SplitPanel,
  events: {
      "onFilmReposition": "film-reposition"
  }
})

export const FilmStack = createComponent({
  react: React,
  tagName: "film-stack",
  elementClass: Stack
})

export const FilmStep = createComponent({
  react: React,
  tagName: "film-step",
  elementClass: Step
})

export const FilmSteps = createComponent({
  react: React,
  tagName: "film-steps",
  elementClass: Steps
})

export const FilmSwitch = createComponent({
  react: React,
  tagName: "film-switch",
  elementClass: Switch,
  events: {
      "onChange": "change"
  }
})

export const FilmSwitcher = createComponent({
  react: React,
  tagName: "film-switcher",
  elementClass: Switcher
})

export const FilmTab = createComponent({
  react: React,
  tagName: "film-tab",
  elementClass: Tab
})

export const FilmTabPanel = createComponent({
  react: React,
  tagName: "film-tab-panel",
  elementClass: TabPanel
})

export const FilmTable = createComponent({
  react: React,
  tagName: "film-table",
  elementClass: Table,
  events: {
      "onFilmSort": "film-sort",
      "onFilmSelectionChange": "film-selection-change",
      "onFilmRowActivate": "film-row-activate"
  }
})

export const FilmTabs = createComponent({
  react: React,
  tagName: "film-tabs",
  elementClass: Tabs,
  events: {
      "onFilmTabChange": "film-tab-change"
  }
})

export const FilmTag = createComponent({
  react: React,
  tagName: "film-tag",
  elementClass: Tag,
  events: {
      "onFilmRemove": "film-remove"
  }
})

export const FilmText = createComponent({
  react: React,
  tagName: "film-text",
  elementClass: Text
})

export const FilmTextarea = createComponent({
  react: React,
  tagName: "film-textarea",
  elementClass: Textarea,
  events: {
      "onChange": "change"
  }
})

export const FilmToast = createComponent({
  react: React,
  tagName: "film-toast",
  elementClass: Toast,
  events: {
      "onFilmClose": "film-close"
  }
})

export const FilmTooltip = createComponent({
  react: React,
  tagName: "film-tooltip",
  elementClass: Tooltip
})

export const FilmTree = createComponent({
  react: React,
  tagName: "film-tree",
  elementClass: Tree,
  events: {
      "onFilmTreeSelect": "film-tree-select"
  }
})

export const FilmTreeItem = createComponent({
  react: React,
  tagName: "film-tree-item",
  elementClass: TreeItem,
  events: {
      "onFilmTreeExpand": "film-tree-expand"
  }
})

export const FilmVisuallyHidden = createComponent({
  react: React,
  tagName: "film-visually-hidden",
  elementClass: VisuallyHidden
})

export const FilmWindow = createComponent({
  react: React,
  tagName: "film-window",
  elementClass: Window,
  events: {
      "onFilmWindowMove": "film-window-move",
      "onFilmWindowResize": "film-window-resize",
      "onFilmWindowMinimise": "film-window-minimise",
      "onFilmWindowMaximise": "film-window-maximise",
      "onFilmWindowClose": "film-window-close",
      "onFilmWindowMovestart": "film-window-movestart",
      "onFilmWindowMoveend": "film-window-moveend",
      "onFilmWindowFocus": "film-window-focus"
  }
})

export const FilmWorkspace = createComponent({
  react: React,
  tagName: "film-workspace",
  elementClass: Workspace,
  events: {
      "onFilmWorkspaceLayout": "film-workspace-layout"
  }
})
